services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "node init-db.js && node server.js"
  db:
    image: postgres:latest
    container_name: postgres_todo
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
